/**
 * 柚子社角色数据库
 * Design: Galgame UI 拟态设计 - 视觉小说界面还原
 * 数据来源：萌娘百科、柚子社官网
 */

export interface Character {
  id: string;
  name: string;
  nameJa: string;
  game: string;
  gameJa: string;
  mbti: string;
  traits: string[];
  tagline: string;
  description: string;
  color: string;
  imageUrl: string;
}

export const characters: Character[] = [
  {
    id: "yoshino",
    name: "朝武芳乃",
    nameJa: "朝武 芳乃",
    game: "千恋＊万花",
    gameJa: "千恋＊万花",
    mbti: "ISTJ",
    traits: ["认真负责", "使命感强", "略带冷酷", "擅长舞蹈"],
    tagline: "古板巫女·反差萌绝缘体",
    description: "穗织建实神社的巫女姬，性格略微稳重，稍微带有点冷酷的味道。非常擅长奉纳的舞蹈，有着强烈的使命感和责任心。虽然表面严肃，但内心其实非常温柔。",
    color: "#E8D5F5",
    imageUrl: "https://www.yuzu-soft.com/products/senren/images/chara01_s.png",
  },
  {
    id: "murasame",
    name: "丛雨",
    nameJa: "むらさめ",
    game: "千恋＊万花",
    gameJa: "千恋＊万花",
    mbti: "ENFP",
    traits: ["活泼开朗", "爱撒娇", "胆小怕鬼", "元气满满"],
    tagline: "拔刀白给·合法萝莉神明",
    description: "寄宿在神刀上的少女，本体是小狐仙。性格有小孩子的一面也有大人的一面，基本上是很有元气开朗的女孩子。活泼爱撒娇，被摸头就会害羞，但其实非常胆小，怕幽灵鬼怪。",
    color: "#FFD4E8",
    imageUrl: "https://www.yuzu-soft.com/products/senren/images/chara03_s.png",
  },
  {
    id: "mako",
    name: "常陆茉子",
    nameJa: "常陸 茉子",
    game: "千恋＊万花",
    gameJa: "千恋＊万花",
    mbti: "ISFJ",
    traits: ["忠诚干练", "温柔体贴", "责任感强", "默默守护"],
    tagline: "忠犬护卫·温柔铠甲",
    description: "芳乃的护卫，世代侍奉朝武家。责任感极强，忠诚干练，同时又温柔体贴。总是默默守护在重要的人身边，是最可靠的存在。",
    color: "#C5E8D5",
    imageUrl: "https://www.yuzu-soft.com/products/senren/images/chara02_s.png",
  },
  {
    id: "lena",
    name: "蕾娜",
    nameJa: "レナ・リヒテナウアー",
    game: "千恋＊万花",
    gameJa: "千恋＊万花",
    mbti: "ESFP",
    traits: ["开朗正直", "元气满满", "热情洋溢", "直率可爱"],
    tagline: "北欧阳光·元气留学生",
    description: "来自芬兰的留学生，个性开朗正直，元气满满。对日本文化充满好奇和热情，总是用积极的态度面对一切，是大家的开心果。",
    color: "#FFE4B5",
    imageUrl: "https://www.yuzu-soft.com/products/senren/images/chara04_s.png",
  },
  {
    id: "nene",
    name: "绫地宁宁",
    nameJa: "綾地 寧々",
    game: "魔女的夜宴",
    gameJa: "サノバウィッチ",
    mbti: "ESFJ",
    traits: ["外表可爱", "性格温柔", "善于交际", "隐藏秘密"],
    tagline: "纯情魔女·体面外壳下的温柔内耗",
    description: "外表可爱、性格温柔、善于待人接物，在学园拥有很高的人气。实际上是一名魔女，内心有着不能说的秘密。表面的完美之下，藏着真实而脆弱的自己。",
    color: "#E8C5D5",
    imageUrl: "https://www.yuzu-soft.com/products/sanoba/images/chara01_s.png",
  },
  {
    id: "tsumugi",
    name: "椎叶紬",
    nameJa: "椎葉 紬",
    game: "魔女的夜宴",
    gameJa: "サノバウィッチ",
    mbti: "INFP",
    traits: ["温柔文静", "大和抚子", "内心丰富", "理想主义"],
    tagline: "温柔文静·大和抚子",
    description: "温柔文静的大和抚子型女孩，内心世界非常丰富。对美好事物有着天生的感知力，是一个充满理想主义色彩的浪漫少女。",
    color: "#D5C5E8",
    imageUrl: "https://www.yuzu-soft.com/products/sanoba/images/chara04_s.png",
  },
  {
    id: "meguru",
    name: "因幡巡",
    nameJa: "因幡 めぐる",
    game: "魔女的夜宴",
    gameJa: "サノバウィッチ",
    mbti: "ENFJ",
    traits: ["元气直率", "热情感染", "善解人意", "领导力强"],
    tagline: "元气直率·热情感染力",
    description: "元气活泼、直率可爱的女孩子。拥有极强的感染力和领导力，总能带动周围人的情绪。善解人意，是大家都喜欢的类型。",
    color: "#FFD5C5",
    imageUrl: "https://www.yuzu-soft.com/products/sanoba/images/chara02_s.png",
  },
  {
    id: "ayase",
    name: "三司绫濑",
    nameJa: "三司 綾瀬",
    game: "RIDDLE JOKER",
    gameJa: "RIDDLE JOKER",
    mbti: "ENTJ",
    traits: ["完美主义", "傲娇", "猫控", "表里不一"],
    tagline: "完美会长·傲娇猫控",
    description: "学生会长，性格傲娇。对外粉饰自己的性格，以一副完美女生的姿态应对他人。对猫有着难以想象的痴迷，仅仅是在屏幕上见到猫就会进入变态模式。",
    color: "#C5D5E8",
    imageUrl: "https://www.yuzu-soft.com/products/riddle/images/chara01_s.png",
  },
  {
    id: "nanami",
    name: "在原七海",
    nameJa: "在原 七海",
    game: "RIDDLE JOKER",
    gameJa: "RIDDLE JOKER",
    mbti: "ISFP",
    traits: ["家务万能", "朴实温柔", "怕生", "成熟可靠"],
    tagline: "朴实妹妹·温柔守护者",
    description: "主人公的妹妹（无血缘关系）。家务万能，性格朴实，但又有着成熟的一面。刚见面时会特别怕生，熟络后会变得非常亲近和依赖。",
    color: "#E8E5C5",
    imageUrl: "https://www.yuzu-soft.com/products/riddle/images/chara04_s.png",
  },
  {
    id: "chisaki",
    name: "壬生千咲",
    nameJa: "壬生 千咲",
    game: "RIDDLE JOKER",
    gameJa: "RIDDLE JOKER",
    mbti: "INFJ",
    traits: ["温柔善良", "治愈系", "洞察力强", "内心坚定"],
    tagline: "治愈天使·温柔洞察者",
    description: "温柔善良的治愈系女孩，拥有敏锐的洞察力，总能察觉到他人的情绪变化。虽然外表柔弱，但内心非常坚定，是能给人安心感的存在。",
    color: "#C5E8E5",
    imageUrl: "https://www.yuzu-soft.com/products/riddle/images/chara02_s.png",
  },
  {
    id: "kanna",
    name: "明月栞那",
    nameJa: "明月 栞那",
    game: "星光咖啡馆与死神之蝶",
    gameJa: "喫茶ステラと死神の蝶",
    mbti: "INTP",
    traits: ["悠然自得", "阅历丰富", "爱捉弄人", "智慧深邃"],
    tagline: "百年死神·悠然智者",
    description: "活过百年以上的死神女。待人非常友善，性格十分随和，偶尔会得意忘形捉弄别人，发出「尼嘻嘻」的笑声。有时也会表现出阅历丰富、饱经沧桑的一面。",
    color: "#D5E8C5",
    imageUrl: "https://www.yuzu-soft.com/products/stella/images/chara02_s.png",
  },
  {
    id: "natsume",
    name: "四季夏目",
    nameJa: "四季 ナツメ",
    game: "星光咖啡馆与死神之蝶",
    gameJa: "喫茶ステラと死神の蝶",
    mbti: "INTJ",
    traits: ["高岭之花", "不善表达", "内心细腻", "独立自主"],
    tagline: "发卡姬·冷面高岭之花",
    description: "在学校拥有很高的人气，多次拒绝别人的表白，被称为「无情的发卡姬」。不擅长摆出开朗的笑容，喜欢去安静的正统酒吧小酌。外表冷淡但内心其实很细腻。",
    color: "#E8C5C5",
    imageUrl: "https://www.yuzu-soft.com/products/stella/images/chara03_s.png",
  },
  {
    id: "noa",
    name: "白雪乃爱",
    nameJa: "白雪乃愛",
    game: "天使☆嚣嚣 RE-BOOT!",
    gameJa: "天使☆騒々 RE-BOOT!",
    mbti: "ISTP",
    traits: ["沉着冷静", "好奇心强", "诚挚认真", "行动派"],
    tagline: "沉着天使·好奇探索者",
    description: "天使。遇事沉着冷静，对天使的工作十分上心，对待身边的人也很诚挚。一直过着天使的生活，几乎从未接触过人类文明，对漫画、动画、美食等充满好奇。",
    color: "#F0E8FF",
    imageUrl: "https://www.yuzu-soft.com/products/tensou/images/chara01_s.png",
  },
  {
    id: "amane",
    name: "谷风天音",
    nameJa: "谷風 天音",
    game: "天使☆嚣嚣 RE-BOOT!",
    gameJa: "天使☆騒々 RE-BOOT!",
    mbti: "ENTP",
    traits: ["机智灵活", "有点怕生", "魔族血统", "话多有趣"],
    tagline: "魔族妹妹·机智话痨",
    description: "主人公的妹妹，前世是异世界的魔族。性格还算开朗，就是有点怕生。机智灵活，脑子转得很快，总能想出各种有趣的点子。",
    color: "#FFE8D5",
    imageUrl: "https://www.yuzu-soft.com/products/tensou/images/chara04_s.png",
  },
  {
    id: "miu",
    name: "矢来美羽",
    nameJa: "矢来 美羽",
    game: "DRACU-RIOT!",
    gameJa: "DRACU-RIOT!",
    mbti: "ESTJ",
    traits: ["责任感强", "铁面执法", "正义感", "教导型"],
    tagline: "风纪吸血鬼·铁面执法者",
    description: "吸血鬼少女，特区事务管理局风纪班所属。责任感很强，属于会好好教导他人的类型。虽然看起来很严厉，但其实是为了大家好。",
    color: "#E8D5C5",
    imageUrl: "https://www.yuzu-soft.com/products/dracu/images/chara02_s.png",
  },
  {
    id: "sana",
    name: "佐奈",
    nameJa: "佐奈",
    game: "天神乱漫",
    gameJa: "天神乱漫",
    mbti: "ESTP",
    traits: ["天真烂漫", "行动力强", "冒险精神", "直觉敏锐"],
    tagline: "天真神明·冒险行动派",
    description: "神明少女，天真烂漫，活泼开朗。拥有超强的行动力和冒险精神，想到什么就去做。直觉非常敏锐，总能在关键时刻做出正确的判断。",
    color: "#C5E8C5",
    imageUrl: "https://www.yuzu-soft.com/products/tenshin/images/chara01_s.png",
  },
];

export const mbtiDescriptions: Record<string, { title: string; description: string }> = {
  ISTJ: { title: "检查者", description: "安静、严肃、通过全面和可靠来获得成功。实际、有序、注重事实、逻辑和细节。" },
  ISFJ: { title: "守护者", description: "安静、友好、负责任和有良心。坚定地履行义务，为他人和社区服务。" },
  INFJ: { title: "咨询师", description: "寻求意义和联系。想要了解什么激励人们，对他人有洞察力。" },
  INTJ: { title: "策划者", description: "有独创性的思想和强大的驱动力来实现自己的想法和目标。" },
  ISTP: { title: "工匠", description: "容忍和灵活，安静地观察直到问题出现，然后迅速行动找到可行的解决方案。" },
  ISFP: { title: "作曲家", description: "安静、友好、敏感和善良。享受当下，享受周围发生的事情。" },
  INFP: { title: "治愈者", description: "理想主义、忠诚，对自己重视的人和事业有强烈的荣誉感。" },
  INTP: { title: "建筑师", description: "寻求对感兴趣的事物进行逻辑解释。理论性强，对想法比社交互动更感兴趣。" },
  ESTP: { title: "推动者", description: "灵活和容忍，采取务实的方法，专注于即时结果。" },
  ESFP: { title: "表演者", description: "外向、友好和接受。热爱生活、人和物质享受。" },
  ENFP: { title: "冠军", description: "热情、有想象力。把生活看作充满可能性。能迅速在事件和信息之间建立联系。" },
  ENTP: { title: "发明家", description: "机智、灵活、有创造力。善于解决新的和有挑战性的问题。" },
  ESTJ: { title: "监督者", description: "实际、现实、注重事实。果断，迅速行动来实施决策。" },
  ESFJ: { title: "供应者", description: "热心、有良心、合作。希望与他人和谐相处，忠诚。" },
  ENFJ: { title: "教师", description: "热情、有同理心、负责任。高度关注他人的情绪和需求。" },
  ENTJ: { title: "指挥官", description: "坦率、果断，善于领导。能迅速看到不合逻辑和低效的程序和政策。" },
};

export function getCharacterByMbti(mbti: string): Character | undefined {
  return characters.find(c => c.mbti === mbti);
}

export function getGameList(): string[] {
  return Array.from(new Set(characters.map(c => c.game)));
}
